language: rust
sudo: false

rust:
  - stable
  - beta
  - nightly

before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH

script:
  - cargo build
  - cargo test
  - cargo test --examples
  - cargo test --features "i128"
  - cargo test --examples --features "i128"
  - cargo doc --no-deps

notifications:
  email:
    on_success: never
