language: rust
sudo: false

rust:
  - stable
  - beta
  - nightly

before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH

script:
  - cargo build
  - cargo test
  - cargo doc --no-deps

after_success:
  - travis-cargo doc-upload

notifications:
  email:
    on_success: never
