[package]
name = "tokio-serde-bincode"
version = "0.1.0"
authors = ["Carl Lerche <me@carllerche.com>",
           "Alex Crichton <alex@alexcrichton.com>"]

[dependencies]
futures = "0.1"
bytes = "0.4"
tokio-serde = "0.1"
serde = "1.0"
bincode = "0.8"
